# Generated by Django 4.2 on 2023-04-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_searchmodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodel',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
